// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace Microsoft.Azure.Management.Reservations.Models
{
    /// <summary> Calculate exchange request. </summary>
    public partial class CalculateExchangeContent
    {
        /// <summary> Initializes a new instance of CalculateExchangeContent. </summary>
        public CalculateExchangeContent()
        {
        }

        /// <summary> Calculate exchange request properties. </summary>
        public CalculateExchangeRequestProperties Properties { get; set; }
    }
}
