// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace Microsoft.Azure.Management.Reservations.Models
{
    /// <summary> The PatchPropertiesRenewProperties. </summary>
    internal partial class PatchPropertiesRenewProperties
    {
        /// <summary> Initializes a new instance of PatchPropertiesRenewProperties. </summary>
        public PatchPropertiesRenewProperties()
        {
        }

        /// <summary> Gets or sets the purchase properties. </summary>
        public PurchaseRequest PurchaseProperties { get; set; }
    }
}
